In [14]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('https://raw.githubusercontent.com/cdguarnizo/MAPE_ITM/master/02_PruebasHipotesis/HeightWeight.csv')

In [3]:
df.head()

Person   Height   Weight
0       1       69      153
1       2       74      175
2       3       68      155
3       4       70      135
4       5       72      172

In [10]:
df.columns

Index(['Person', ' Height', ' Weight'], dtype='object')

In [13]:
Y=df[[' Height', ' Weight']].values

In [31]:
u0=np.array([[68],[160]])
uy=np.mean(Y,axis=0).reshape(2,1)
Sigma = np.array([[20,100],[100,1000]])
n=20
print(u0,uy,Sigma)

[[ 68]
 [160]] [[ 71.45]
 [164.7 ]] [[  20  100]
 [ 100 1000]]


In [32]:
d=uy-u0
Z=n*d.T@np.linalg.solve(Sigma,d)
print(Z)

[[18.2026]]


In [33]:
from scipy.stats import chi2
prob = 0.95
dof = 2
critical = chi2.ppf(prob, dof)
print(critical)
if abs(Z) >= critical:
  print('Rechazar H0')
else:
  print('Aceptar H0')

5.991464547107979
Rechazar H0


In [36]:
S = np.cov(Y.T,bias=False)
print(S)

[[  14.57631579  128.87894737]
 [ 128.87894737 1441.27368421]]


In [37]:
T=Z=n*d.T@np.linalg.solve(S,d)

In [39]:
from scipy.stats import f
prob = 0.95
p = 2
n = 20
v = n-1
critical = f.ppf(prob, p,v-p+1)*(v*p)/(v-p+1) #ver eq. 5.7 Rencher

if abs(T) >= critical:
  print('Rechazar H0')
else:
  print('Aceptar H0')

Rechazar H0


test psicologio

In [40]:
pdf=pd.read_csv('https://raw.githubusercontent.com/cdguarnizo/MAPE_ITM/master/02_PruebasHipotesis/FourPsychological.csv')

In [42]:
pdf.head()

m1   m2   m3   m4   f1   f2   f3   f4
0  15   17   24   14   13   14   12   21
1  17   15   32   26   14   12   14   26
2  15   14   29   23   12   19   21   21
3  13   12   10   16   12   13   10   16
4  20   17   26   28   11   20   16   16

In [44]:
males = pdf[pdf.columns[:4]]
famales = pdf[pdf.columns[4:]]

In [45]:
males.sample(3)

m1   m2   m3   m4
2   15   14   29   23
0   15   17   24   14
14  18   18   31   27

In [46]:
famales.sample(3)

f1   f2   f3   f4
26   14   17   24   23
5    12    9   14   18
4    11   20   16   16

In [51]:
males_mean = males.mean().values
males_var = males.cov().values

print("mean ",males_mean)
print("cov ",males_var)

mean  [15.96875 15.90625 27.1875  22.75   ]
cov  [[ 5.19254032  4.5453629   6.52217742  5.25      ]
 [ 4.5453629  13.18447581  6.76008065  6.26612903]
 [ 6.52217742  6.76008065 28.6733871  14.46774194]
 [ 5.25        6.26612903 14.46774194 16.64516129]]


In [52]:
famales_mean = famales.mean().values
famales_var = famales.cov().values

print("mean ",famales_mean)
print("cov ",famales_var)

mean  [12.34375 13.90625 16.65625 21.9375 ]
cov  [[ 9.13608871  7.54939516  4.86391129  4.15120968]
 [ 7.54939516 18.60383065 10.22479839  5.44556452]
 [ 4.86391129 10.22479839 30.03931452 13.49395161]
 [ 4.15120968  5.44556452 13.49395161 27.99596774]]


In [53]:
spl=(1/62)*((31*males_var)+(31*famales_var))

In [54]:
spl

array([[ 7.16431452,  6.04737903,  5.69304435,  4.70060484],
       [ 6.04737903, 15.89415323,  8.49243952,  5.85584677],
       [ 5.69304435,  8.49243952, 29.35635081, 13.98084677],
       [ 4.70060484,  5.85584677, 13.98084677, 22.32056452]])

In [58]:
T2=((32*32)/64)*((males_mean-famales_mean).T)@(np.linalg.inv(spl))@(males_mean-famales_mean)

In [59]:
T2

97.60149652776889

In [60]:
from scipy.stats import f
prob = 0.99
p = 4
n1 = 32
n2 = 32
critical = f.ppf(prob, p,n1+n2-p-1)*p*(n1+n2-2)/(n1+n2-p-1) #ver eq 5.11 Rencher
T2 = 97.6015
if abs(T2) >= critical:
  print('Rechazar H0')
else:
  print('Aceptar H0')

Rechazar H0


recubrimiento de tuberias ante la corrosion

In [61]:
tubdf=pd.read_csv('https://raw.githubusercontent.com/cdguarnizo/MAPE_ITM/master/02_PruebasHipotesis/CoatedPipes.csv')

In [62]:
tubdf.tail()

Location   Coating 1 Depth   Coating 1 Number   Coating 2 Depth  \
10        11                56                 19                57   
11        12                34                 19                44   
12        13                55                 26                57   
13        14                65                 15                40   
14        15                75                 18                68   

     Coating 2 Number  
10                 14  
11                 19  
12                 30  
13                  7  
14                 13

In [63]:
tubdf.columns

Index(['Location', ' Coating 1 Depth', ' Coating 1 Number', ' Coating 2 Depth',
       ' Coating 2 Number'],
      dtype='object')

In [66]:
X = tubdf[[' Coating 1 Depth',' Coating 1 Number']].values
Y = tubdf[[' Coating 2 Depth',' Coating 2 Number']].values

In [67]:
d = X-Y

In [69]:
X.shape

(15, 2)

In [74]:
Sd = np.cov(d.T, bias=False)
ud = np.mean(d,axis=0)
print('cov: ',Sd)
print('mean: ',ud)

cov:  [[121.57142857  17.07142857]
 [ 17.07142857  21.78095238]]
mean:  [8.         3.06666667]


In [76]:
T2 = 15*ud.T@np.linalg.solve(Sd,ud)
print(T2)

10.818898540198349


In [77]:
prob = 0.95
p = 2
n = 15
v = n-1
critical = f.ppf(prob, p,v-p+1)*(v*p)/(v-p+1)
if abs(T2) >= critical:
  print('Rechazar H0')
else:
  print('Aceptar H0')

Rechazar H0


In [78]:
critical

8.196602083337353